
server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://www.zym.com:9000/eureka/

spring:
  application:
    name: eureka-server