server:
  port: 7011

eureka:
  instance:
    hostname: www.zym.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/

spring:
  application:
    name: eureka-server