
server:
  port: 7022


eureka:
  server:       #配置关闭自我保护，并按需配置Eureka Server清理无效节点的时间间隔。
      enable-self-preservation: false        #关掉自我保护
      eviction-interval-timer-in-ms: 3000   # 清理间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #
    fetch-registry: false #
   # service-url:
   #   defaultZone: http://www.zym.com:9000/eureka/

spring:
  application:
    name: eureka-server
  mvc:
    servlet:
      load-on-startup: 1