server:
  port: 8010

spring:
  application:
    name: userCenter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
feign:
  compression:
    request:
      min-request-size:
