server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:   #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: false # 是否与服务发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
          lower-case-service-id: true #将服务名转成小写
      routes:
      - id: userCenter
        uri: lb://userCenter
        order: 800
        predicates:
            - Path=/userCenter/**
        filters:
           - RewritePath=/userCenter/(?<segment>.*), /$\{segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7022/eureka/ #,http://www.zym.com:7011/eureka/


logging:
  level:
    root: debug
    org.springframework.cloud.gateway: TRACE
