server:
  port: 80

spring:
  redis:
    host: 127.0.0.1
    password: u2CVLsHGYn4dVh6M4qTMr17iaQk
    pool:
      maxIdle: 5
      minIdle: 2

  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:   #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: false # 是否与服务发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
          lower-case-service-id: true #将服务名转成小写
      routes:
      - id: userCenter
        uri: lb://userCenter
        order: 800
        predicates:
            - Path=/userCenter/**
        filters:
           - RewritePath=/userCenter/(?<segment>.*), /$\{segment}
           - name: RequestRateLimiter
             args:
                redis-rate-limiter.replenishRate: 1 # 令牌桶的容积
                redis-rate-limiter.burstCapacity: 1 # 流速 每秒
                key-resolver: "#{@apiKeyResolver}" #SPEL表达式去的对应的bean
      default-filters:
      - name: RequestRateLimiter
        args:
          redis-rate-limiter.replenishRate: 1 # 令牌桶的容积
          redis-rate-limiter.burstCapacity: 1 # 流速 每秒
          key-resolver: "#{@apiKeyResolver}" #SPEL表达式去的对应的bean
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7022/eureka/ #,http://www.zym.com:7011/eureka/


logging:
  level:
    root: debug
    org.springframework.cloud.gateway: TRACE
