---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhongym.
--- DateTime: 2018/11/14 10:31
---
---
---
local json = require("json")
print(type(2))
print(type("holle word"))
print(type(1))
print(type(true))

print("holle word")
print(1)
print(1.222)

print(true)
print(nil)

print("----------------------------------------")
a = "1"
a = a + 1
print(a)

b = tonumber("1")

html = [[
<html>
<head></head>
<body>
    <a href="http://www.runoob.com/">菜鸟教程</a>
</body>
</html>
]]
print(html)

st = "ad"
st1 = "ac"
-- 字符串拼接
print(st .. st1)

list = {}
list[0] = 20
list["key"] = "value"

function myPrint(v)
    print("---------:  " .. v)
end

for k, v in pairs(list) do
    myPrint(k .. "   " .. v)
end

print("----------------------------循环")
-- while
i = 0
while (i < 10)
do
    print("i:" .. i)
    i = i + 1
end

-- for
--[[
for var=exp1,exp2,exp3 do
    <执行体>
end

var 从 exp1 变化到 exp2，每次变化以 exp3 为步长递增 var，并执行一次 "执行体"。exp3 是可选的，如果不指定，默认为1。
]]

c = 10
for i = 1, c do
    myPrint(i)
end

for i = 1, c, 2 do
    myPrint(i)
end

for i = c, 1, -1 do
    myPrint(i)
end
 
arr = { "a", "b", "c" }
for i, v in ipairs(arr) do
    myPrint(i .. "-" .. v)
end

-- repeat...until 【java 的do while]
d = 10
repeat
    myPrint("dddddddd")
until (d > 9)


print("----------------------------流程控制")

if true then
    myPrint("true")
else
    myPrint("false")
end




local json1 = "[\"com.laimi.store.common.User\",{\"storeId\":150105,\"operId\":10214289,\"storeTitle\":\"13360014323\",\"name\":\"13360014323\",\"mobile\":\"13360014323\",\"loginName\":\"1539592763908\",\"isMobileBind\":true,\"regionId\":3114,\"status\":\"enable\",\"initStatus\":1,\"isInfoComplete\":true,\"isChainStore\":false,\"areaAgentCodes\":[\"java.util.ArrayList\",[\"zskx_fs\"]],\"clientVersion\":[\"com.laimi.store.common.ext.ClientVersion\",{\"appVersion\":\"ios.store.client:2.43.0\",\"kind\":\"ios.store.client\",\"versionNum\":\"2.43.0\",\"android\":false,\"ios\":true}],\"latitude\":23.13971603,\"longitude\":113.36504501,\"province\":\"广东\",\"city\":\"佛山\",\"county\":\"禅城\",\"district\":\"张槎\",\"creationDate\":[\"java.util.Date\",1529543643000],\"deviceId\":\"648F7072-4B7E-4C22-B2E2-06409066F675\",\"mobileBind\":true,\"infoComplete\":true,\"chainStore\":false}]"

local login_user_obj = json.decode(json1)
local j = login_user_obj[2]["operId"]
myPrint(j)