server:
  port: 8020

spring:
  application:
    name: activityCenter

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30 #心跳间隔  这里配置 10 默认是30秒
    leaseExpirationDurationInSeconds: 90 #从注册中心剔除服务的检测间隔  这里配置30 默认90秒
  client:
    service-url:
      defaultZone: http://localhost:7022/eureka/  #,http://www.zym.com:9000/eureka/
